# TOC

__Chapter 1 - Introduction to PyTorch tensors and tensor operations__

1. [Import](#Import)
1. [Recipe 1-1 : Using tensors](#Recipe-1-1-:-Using-tensors)

# Import

<a id = 'Import'></a>

In [1]:
# standard libary and settings
import os
import sys
import importlib
import itertools
import warnings

warnings.simplefilter("ignore")
from IPython.core.display import display, HTML

display(HTML("<style>.container { width:95% !important; }</style>"))

# data extensions and settings
import numpy as np

np.set_printoptions(threshold=np.inf, suppress=True)
import pandas as pd

pd.set_option("display.max_rows", 500)
pd.set_option("display.max_columns", 500)
pd.options.display.float_format = "{:,.6f}".format

import torch

# visualization extensions and settings
import seaborn as sns
import matplotlib.pyplot as plt

# magic functions
%matplotlib inline

In [2]:
torch.version.__version__

'1.0.1'

# Recipe 1-1 : Using tensors

__Problem__: The data structure in PyTorch is graph and tensor based, so it's important to understand basic tensor operations .

__Solution__: Practice various operations to learn PyTorch basics

<a id = 'Recipe-1-1-:-Using-tensors'></a>

In [4]:
# check whether the Python list is a tensor object
x = [12, 23, 34, 45, 56, 78]
print(torch.is_tensor(x))
print(torch.is_storage(x))

False
False


In [6]:
# create an PyTorch object that contains random numbers and check
# if tensor, if storage, and show total # of elements
y = torch.randn(1, 2, 3, 4, 5)
print(torch.is_tensor(y))
print(torch.is_storage(x))
print(torch.numel(y))

True
False
120


In [8]:
# create a matri and show # of elements
torch.zeros(4, 4)
torch.numel(torch.zeros(4, 4))

16

In [9]:
# create eye matrices
print(torch.eye(3, 4))
print(torch.eye(5, 4))

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])


In [10]:
# convert list to numpy array, array to tensor
x1 = np.array(x)
print(x1)
print(torch.from_numpy(x1))

[12 23 34 45 56 78]
tensor([12, 23, 34, 45, 56, 78], dtype=torch.int32)


In [11]:
# create linear space tensor
print(torch.linspace(2, 10, steps=25))

tensor([ 2.0000,  2.3333,  2.6667,  3.0000,  3.3333,  3.6667,  4.0000,  4.3333,
         4.6667,  5.0000,  5.3333,  5.6667,  6.0000,  6.3333,  6.6667,  7.0000,
         7.3333,  7.6667,  8.0000,  8.3333,  8.6667,  9.0000,  9.3333,  9.6667,
        10.0000])


In [12]:
# create tensor of random numbers fro uniform distribution
torch.rand(10)

tensor([0.7530, 0.2944, 0.6050, 0.8143, 0.1549, 0.6544, 0.0131, 0.8060, 0.0938,
        0.4854])

In [18]:
# create tensor of random numbers from uniform distribution
# reshape into a matrix
torch.rand(4, 5)

tensor([[0.2969, 0.6612, 0.9421, 0.6067, 0.7865],
        [0.9169, 0.2195, 0.1074, 0.1302, 0.2437],
        [0.6398, 0.1287, 0.2454, 0.4561, 0.8758],
        [0.2170, 0.8286, 0.8198, 0.8776, 0.4365]])

In [19]:
# create tensor of random numbers drawn from a random
# distribution with a mean of 0 and std of 1
print(torch.randn(10))
print(torch.randn(4, 5))

tensor([-0.4673,  1.4152, -0.5462,  2.2342, -0.0873,  0.3099, -1.3707, -0.1404,
         0.0120, -0.6288])
tensor([[ 1.0763, -0.4663, -1.0329, -0.9713, -1.3553],
        [-0.1807, -0.3559, -0.1414,  0.5992,  1.1845],
        [-0.5061, -1.2895,  0.3020,  1.1136, -0.4574],
        [ 1.7592,  0.3094, -0.2382, -0.8532, -0.5233]])


In [20]:
# randomly select values from a range of values
torch.randperm(10)

tensor([4, 3, 5, 6, 7, 2, 8, 9, 1, 0])

In [21]:
# torch's arange function
torch.arange(10, 40, 2)

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [23]:
# min/max. the dim argument is required if the input is a matrix and then min/max is drawn from the rows or columns
d = torch.randn(4, 5)
torch.argmin(d, dim=1)
torch.argmax(d, dim=1)

tensor([4, 0, 2, 1])

In [24]:
# concatenate tensors
x = torch.randn(4, 5)
torch.cat((x, x))

tensor([[-0.4195,  1.3210, -2.3474, -1.3669,  1.4421],
        [-0.4975,  0.7090,  0.4747, -0.5935,  1.1285],
        [-0.3521, -0.2824,  0.5955, -1.0892,  0.5155],
        [ 1.5931,  0.5624, -0.0434,  0.1085, -0.3073],
        [-0.4195,  1.3210, -2.3474, -1.3669,  1.4421],
        [-0.4975,  0.7090,  0.4747, -0.5935,  1.1285],
        [-0.3521, -0.2824,  0.5955, -1.0892,  0.5155],
        [ 1.5931,  0.5624, -0.0434,  0.1085, -0.3073]])

In [25]:
# separate and input matrix into chunks, row-wise
# 2 different options
a = torch.randn(4, 4)
print(a)
print(torch.chunk(a, 2))
print(torch.chunk(a, 2, 0))

tensor([[-0.7811,  1.9552, -1.4225, -0.2837],
        [-0.0360, -1.5801, -0.0917,  0.4939],
        [-1.1010,  0.4755, -0.3136,  0.1668],
        [ 1.0221,  1.3428,  0.3092,  2.1407]])
(tensor([[-0.7811,  1.9552, -1.4225, -0.2837],
        [-0.0360, -1.5801, -0.0917,  0.4939]]), tensor([[-1.1010,  0.4755, -0.3136,  0.1668],
        [ 1.0221,  1.3428,  0.3092,  2.1407]]))
(tensor([[-0.7811,  1.9552, -1.4225, -0.2837],
        [-0.0360, -1.5801, -0.0917,  0.4939]]), tensor([[-1.1010,  0.4755, -0.3136,  0.1668],
        [ 1.0221,  1.3428,  0.3092,  2.1407]]))


In [26]:
# separate and input matrix into chunks, column-wise
print(torch.chunk(a, 2, 1))

(tensor([[-0.7811,  1.9552],
        [-0.0360, -1.5801],
        [-1.1010,  0.4755],
        [ 1.0221,  1.3428]]), tensor([[-1.4225, -0.2837],
        [-0.0917,  0.4939],
        [-0.3136,  0.1668],
        [ 0.3092,  2.1407]]))


In [27]:
# use LongTensor to select relevant rows from tensor
a = torch.randn(4, 4)
print(a)
indices = torch.LongTensor([0, 2])
print(torch.index_select(a, 0, indices))

tensor([[-0.3430, -0.2768, -2.0120, -0.8449],
        [ 0.4486,  0.2183, -0.6365,  0.8927],
        [-0.5289, -0.3575, -0.1382, -0.3390],
        [ 0.1891,  0.4728,  0.5133,  0.5057]])
tensor([[-0.3430, -0.2768, -2.0120, -0.8449],
        [-0.5289, -0.3575, -0.1382, -0.3390]])


In [28]:
# select relevant columns from tensor
print(torch.index_select(a, 1, indices))

tensor([[-0.3430, -2.0120],
        [ 0.4486, -0.6365],
        [-0.5289, -0.1382],
        [ 0.1891,  0.5133]])


In [29]:
# check for non-zero values
print(torch.nonzero(torch.tensor([10, 00, 23, 0, 0.0])))
print(torch.nonzero(torch.Tensor([10, 00, 23, 0, 0.0])))

tensor([[0],
        [2]])
tensor([[0],
        [2]])


In [32]:
# split a long tensor into smaller tensors
print(torch.split(torch.tensor([12, 21, 34, 32, 45, 54, 56, 54]), 2))
print(torch.split(torch.tensor([12, 21, 34, 32, 45, 54, 56, 54]), 3))

(tensor([12, 21]), tensor([34, 32]), tensor([45, 54]), tensor([56, 54]))
(tensor([12, 21, 34]), tensor([32, 45, 54]), tensor([56, 54]))


In [36]:
# reshape tensors using transpose
print(x)
print(x.t())
print(x.transpose(1, 0))

tensor([[-0.4195,  1.3210, -2.3474, -1.3669,  1.4421],
        [-0.4975,  0.7090,  0.4747, -0.5935,  1.1285],
        [-0.3521, -0.2824,  0.5955, -1.0892,  0.5155],
        [ 1.5931,  0.5624, -0.0434,  0.1085, -0.3073]])
tensor([[-0.4195, -0.4975, -0.3521,  1.5931],
        [ 1.3210,  0.7090, -0.2824,  0.5624],
        [-2.3474,  0.4747,  0.5955, -0.0434],
        [-1.3669, -0.5935, -1.0892,  0.1085],
        [ 1.4421,  1.1285,  0.5155, -0.3073]])
tensor([[-0.4195, -0.4975, -0.3521,  1.5931],
        [ 1.3210,  0.7090, -0.2824,  0.5624],
        [-2.3474,  0.4747,  0.5955, -0.0434],
        [-1.3669, -0.5935, -1.0892,  0.1085],
        [ 1.4421,  1.1285,  0.5155, -0.3073]])


In [38]:
# use unbind function to remove a column from a tensor
print(x)
print(torch.unbind(x, 1))

tensor([[-0.4195,  1.3210, -2.3474, -1.3669,  1.4421],
        [-0.4975,  0.7090,  0.4747, -0.5935,  1.1285],
        [-0.3521, -0.2824,  0.5955, -1.0892,  0.5155],
        [ 1.5931,  0.5624, -0.0434,  0.1085, -0.3073]])
(tensor([-0.4195, -0.4975, -0.3521,  1.5931]), tensor([ 1.3210,  0.7090, -0.2824,  0.5624]), tensor([-2.3474,  0.4747,  0.5955, -0.0434]), tensor([-1.3669, -0.5935, -1.0892,  0.1085]), tensor([ 1.4421,  1.1285,  0.5155, -0.3073]))


In [39]:
# use unbind function to remove a row from a tensor
print(x)
print(torch.unbind(x, 0))

tensor([[-0.4195,  1.3210, -2.3474, -1.3669,  1.4421],
        [-0.4975,  0.7090,  0.4747, -0.5935,  1.1285],
        [-0.3521, -0.2824,  0.5955, -1.0892,  0.5155],
        [ 1.5931,  0.5624, -0.0434,  0.1085, -0.3073]])
(tensor([-0.4195,  1.3210, -2.3474, -1.3669,  1.4421]), tensor([-0.4975,  0.7090,  0.4747, -0.5935,  1.1285]), tensor([-0.3521, -0.2824,  0.5955, -1.0892,  0.5155]), tensor([ 1.5931,  0.5624, -0.0434,  0.1085, -0.3073]))


In [40]:
# basic addition of a scalar to a matrix
print(x)
print(torch.add(x, 20))

tensor([[-0.4195,  1.3210, -2.3474, -1.3669,  1.4421],
        [-0.4975,  0.7090,  0.4747, -0.5935,  1.1285],
        [-0.3521, -0.2824,  0.5955, -1.0892,  0.5155],
        [ 1.5931,  0.5624, -0.0434,  0.1085, -0.3073]])
tensor([[19.5805, 21.3210, 17.6526, 18.6331, 21.4421],
        [19.5025, 20.7090, 20.4747, 19.4065, 21.1285],
        [19.6479, 19.7176, 20.5955, 18.9108, 20.5155],
        [21.5931, 20.5624, 19.9566, 20.1085, 19.6927]])


In [41]:
# basic multiplication of a matrix by a scalr
print(x)
print(torch.mul(x, 2))

tensor([[-0.4195,  1.3210, -2.3474, -1.3669,  1.4421],
        [-0.4975,  0.7090,  0.4747, -0.5935,  1.1285],
        [-0.3521, -0.2824,  0.5955, -1.0892,  0.5155],
        [ 1.5931,  0.5624, -0.0434,  0.1085, -0.3073]])
tensor([[-0.8391,  2.6420, -4.6949, -2.7337,  2.8842],
        [-0.9951,  1.4179,  0.9495, -1.1869,  2.2569],
        [-0.7042, -0.5648,  1.1909, -2.1784,  1.0310],
        [ 3.1862,  1.1248, -0.0868,  0.2170, -0.6146]])


In [46]:
# express linear equation using tensor operations
intercept = torch.randn(1)
x = torch.randn(2, 2)
beta = 0.7456

print(torch.mul(intercept, x))
print(torch.mul(x, beta))

# y = intercept + (beta * x)
print(torch.add(torch.mul(intercept, x), torch.mul(x, beta)))

tensor([[ 1.2627,  1.0525],
        [-0.0292, -0.4568]])
tensor([[ 1.2074,  1.0064],
        [-0.0279, -0.4368]])
tensor([[ 2.4702,  2.0589],
        [-0.0570, -0.8936]])


In [49]:
# round using floor and ceil
torch.manual_seed(1234)
x = torch.randn(5, 5)
print(torch.ceil(x))
print(torch.floor(x))

tensor([[-0., -0.,  1., -0.,  1.],
        [ 1., -0., -0., -0., -0.],
        [-1., -0.,  1., -0.,  2.],
        [ 1., -1.,  2., -0., -0.],
        [-1.,  1., -0.,  1.,  1.]])
tensor([[-1., -1.,  0., -1.,  0.],
        [ 0., -1., -1., -1., -1.],
        [-2., -1.,  0., -1.,  1.],
        [ 0., -2.,  1., -1., -1.],
        [-2.,  0., -1.,  0.,  0.]])


In [50]:
# limit the values of a tensor to be within a certain range using the
# minimum and maximum arguments along with the clamp function.
torch.clamp(torch.floor(x), min=-0.3, max=0.4)

tensor([[-0.3000, -0.3000,  0.0000, -0.3000,  0.0000],
        [ 0.0000, -0.3000, -0.3000, -0.3000, -0.3000],
        [-0.3000, -0.3000,  0.0000, -0.3000,  0.4000],
        [ 0.0000, -0.3000,  0.4000, -0.3000, -0.3000],
        [-0.3000,  0.0000, -0.3000,  0.0000,  0.0000]])

In [51]:
# truncate with only lower limit

torch.clamp(torch.floor(x), min=-0.3)

tensor([[-0.3000, -0.3000,  0.0000, -0.3000,  0.0000],
        [ 0.0000, -0.3000, -0.3000, -0.3000, -0.3000],
        [-0.3000, -0.3000,  0.0000, -0.3000,  1.0000],
        [ 0.0000, -0.3000,  1.0000, -0.3000, -0.3000],
        [-0.3000,  0.0000, -0.3000,  0.0000,  0.0000]])

In [53]:
# truncate with only upper limit
torch.clamp(torch.floor(x), max=0.3)

tensor([[-1.0000, -1.0000,  0.0000, -1.0000,  0.0000],
        [ 0.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-2.0000, -1.0000,  0.0000, -1.0000,  0.3000],
        [ 0.0000, -2.0000,  0.3000, -1.0000, -1.0000],
        [-2.0000,  0.0000, -1.0000,  0.0000,  0.0000]])

In [56]:
# compute the exponential of a tensor
x = torch.randn(2, 2)
torch.exp(x)

tensor([[0.5295, 1.1467],
        [1.5830, 1.5994]])

In [58]:
# compute the log of the values in the tensor
print(x)
print(torch.log(x))

tensor([[-0.6359,  0.1369],
        [ 0.4593,  0.4696]])
tensor([[    nan, -1.9886],
        [-0.7780, -0.7559]])


In [59]:
# take tensor values to a specified power
print(torch.pow(x, 2))

tensor([[0.4043, 0.0187],
        [0.2110, 0.2205]])


In [60]:
# apply sigmoid function to a tensor
torch.sigmoid(x)

tensor([[0.3462, 0.5342],
        [0.6129, 0.6153]])

In [61]:
# take square root of tensor
torch.sqrt(x)

tensor([[   nan, 0.3700],
        [0.6777, 0.6853]])